# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        fetch-depth: 0
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --tee --output flake8stats.txt
    - name: Test with pytest
      run: |
        set -o pipefail
        pytest | tee pytest_log.txt
    - name: Genbadge
      if: ${{ github.event_name == 'push' }}
      run: |
        genbadge tests -i junit.xml
        genbadge coverage -i coverage.xml
        genbadge flake8 -i flake8stats.txt
        git checkout badges
        git pull
        mkdir -p badges reports
        mv tests-badge.svg coverage-badge.svg flake8-badge.svg badges/
        mv flake8stats.txt pytest_log.txt reports/
        git config --local user.email "duyantao2009@gmail.com"
        git config --local user.name "Yantao Du"
        git add badges/* reports/*
        git commit --allow-empty -m 'Update badges'
    - name: Push badge commit
      uses: ad-m/github-push-action@master
      if: ${{ github.event_name == 'push' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: badges
